kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: b2-state-db-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: b2-state-db-pv
  storageClassName: ""
  volumeMode: Filesystem
