apiVersion: apps/v1
kind: Deployment
metadata:
  name: statedb
spec:
  selector:
    matchLabels:
      app: statedb
  replicas: 1
  template:
    metadata:
      labels:
        app: statedb
    spec:
      containers:
      - name: statedb
        image: postgres:15-alpine
        volumeMounts:
        # - name: datadir
        #   mountPath: /mnt/source
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init_prover_db.sql
          readOnly: true
        env:
        - name: POSTGRES_USER
          value: state_user
        - name: POSTGRES_PASSWORD
          value: state_password
        - name: POSTGRES_DB
          value: state_db
        resources:
          limits:
            cpu: 0.5
            memory: 0.5Gi

      restartPolicy: Always
      volumes:
      # - name: datadir
      #   persistentVolumeClaim:
      #     claimName: b2-state-db-pvc
      #     readOnly: false
      - name: init-sql
        configMap:
          name: init-sql
          optional: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pooldb
spec:
  selector:
    matchLabels:
      app: pooldb
  replicas: 1
  template:
    metadata:
      labels:
        app: pooldb
    spec:
      containers:
      - name: pooldb
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: pool_user
        - name: POSTGRES_PASSWORD
          value: pool_password
        - name: POSTGRES_DB
          value: pool_db
        resources:
          limits:
            cpu: 0.5
            memory: 0.5Gi
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventdb
spec:
  selector:
    matchLabels:
      app: eventdb
  replicas: 1
  template:
    metadata:
      labels:
        app: eventdb
    spec:
      containers:
      - name: eventdb
        image: postgres:15-alpine
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init_event_db.sql
          readOnly: true
        env:
        - name: POSTGRES_USER
          value: event_user
        - name: POSTGRES_PASSWORD
          value: event_password
        - name: POSTGRES_DB
          value: event_db
        resources:
          limits:
            cpu: 0.5
            memory: 0.5Gi

      restartPolicy: Always
      volumes:
      - name: init-sql
        configMap:
          name: init-sql
          optional: false


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l1
spec:
  selector:
    matchLabels:
      app: l1
  replicas: 1
  template:
    metadata:
      labels:
        app: l1
    spec:
      containers:
      - name: l1
        image: ghcr.io/b2network/b2-node:20231222-145531-18655e6-with-datadir-6baf597
        command: ["ethermintd", "start"]
        envFrom:
        - configMapRef:
            name: l1-bitcoin-component-cm
        resources:
          limits:
            cpu: 0.5
            memory: 0.5Gi
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prover
spec:
  selector:
    matchLabels:
      app: prover
  replicas: 1
  template:
    metadata:
      labels:
        app: prover
    spec:
      containers:
      - name: prover
        image: ghcr.io/b2network/b2-zkevm-prover:20231127-164129-7accb0b
        volumeMounts:
        - name: config
          mountPath: /usr/src/app/config.json
          subPath: prover-config.json
          readOnly: true
        args:
        - -c
        - /usr/src/app/config.json
        resources:
          limits:
            cpu: 2
            memory: 2Gi
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: prover-config
          optional: false
