resources:
- deploy.yml
- pv.yml
- pvc.yml
- svc.yml

configMapGenerator:
- name: init-sql
  files:
  - ./init_prover_db.sql
  - ./init_event_db.sql

- name: l1-bitcoin-component-cm
  files:
  - ./bitcoin.env
