apiVersion: v1
kind: Service
metadata:
  name: zkevm-state-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: statedb
---
apiVersion: v1
kind: Service
metadata:
  name: l1
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: l1
