apiVersion: v1
kind: Service
metadata:
  name: zkevm-state-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: statedb

---
apiVersion: v1
kind: Service
metadata:
  name: zkevm-pool-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: pooldb

---
apiVersion: v1
kind: Service
metadata:
  name: zkevm-event-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: eventdb

---
apiVersion: v1
kind: Service
metadata:
  name: l1
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: l1

---
apiVersion: v1
kind: Service
metadata:
  name: prover
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: prover

---
apiVersion: v1
kind: Service
metadata:
  name: l2-rpc
spec:
  type: NodePort
  selector:
    app: l2-rpc
  ports:
    - name: rpc
      protocol: TCP
      port: 8123
      nodePort: 30001
