apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx-http
      protocol: TCP
      port: 80
      targetPort: 12346
      nodePort: 30628
